---

- name: Install requirements first
  include: requirements.yml
  tags: ['firewall-install']

- name: Install firewall
  include: install.yml
  tags: ['firewall-install']

- name: Install firewall-ipv6
  include: install-ipv6.yml
  tags: ['firewall-install']

- name: Configure monit
  include: monit.yml
  tags: ['firewall-monit']