---
- name: restart firewall
  service:
    name: 'firewall'
    state: restarted
    enabled: yes

- name: reload systemd
  command: systemctl daemon-reload

- name: reload monit
  command: monit reload